### PR TITLE
Backend Integration

### PR DESCRIPTION
**Pull request by dush-t**
The static files are placed inside the app directory instead of the base directory. I did that merely out of habit. Also removed some string formatters because for some reason they were raising errors. The code seems to work fine without them. @ashryaagr please tell me why you included those.

Since the original form on the sign up page had only a _team name_ and a _password_ field, I had to insert two more fields (namely id1 and id2), since our current data models require them during registration. This has messed up the front-end a bit.

### CODE REVIEW

**Comment by apb7** [comment]
@dush-t: just a suggestion: before making any breaking changes, discuss the approach with everyone -- you shouldn't mess "up the front-end a bit".
@sharifa2708 @Saujas please do a full review before merging.
Thanks!

**Comment by dush-t** [comment]
@apb7 I had actually discussed this with Rohit before doing it.

**Comment by Saujas** [comment]
@dush-t there is no check on the bits ID being done

**Comment by Saujas** [comment]
Also, why did you remove the confirm password?

**Comment by Saujas** [comment]
And @ashryaagr @dush-t , what about the main game integration? By when will that be done?

**Comment by dush-t** [comment]
@Saujas about the check - I noticed that and @ashryaagr will implement that. As for the confirm password, I did not know there was such a field since I didn't see it being used anywhere in our views. I will fix it ASAP.

**Comment by dush-t** [comment]
@Saujas I will work on it today after 6 pm. It will be done before tomorrow midnight.

**Comment by Saujas** [comment]
Agree about the messing up the frontend part, talk to the frontend juniors to try to fit everything properly within the page

**Pull request merged**
